pipeline {
    agent any

    environment {
        BLUE_HOST = "13.238.248.58"
        GREEN_HOST = "13.54.192.16"
        PROJECT_DIR = "/home/ubuntu/graphic-design-tool/graphic-design-tool-main"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Workspace') {
            steps {
                sh '''
                    echo "===== WORKSPACE ====="
                    pwd
                    ls -la
                '''
            }
        }

        stage('Test SSH Connection') {
            steps {
                sshagent(credentials: ['blue-green-key']) {
                    sh '''
                        echo "===== SSH KEYS LOADED IN AGENT ====="
                        ssh-add -l

                        echo ""
                        echo "===== BLUE SERVER ====="

                        ssh -o StrictHostKeyChecking=no \
                        -o UserKnownHostsFile=/dev/null \
                        ubuntu@$BLUE_HOST <<EOF
hostname
pwd
ls -ld $PROJECT_DIR
EOF

                        echo ""
                        echo "===== GREEN SERVER ====="

                        ssh -o StrictHostKeyChecking=no \
                        -o UserKnownHostsFile=/dev/null \
                        ubuntu@$GREEN_HOST <<EOF
hostname
pwd
ls -ld $PROJECT_DIR
EOF
                    '''
                }
            }
        }

        stage('Deploy Backend to Green') {
            steps {
                sshagent(credentials: ['blue-green-key']) {
                    sh '''
                        echo "===== DEPLOYING BACKEND TO GREEN ====="

                        ssh -o StrictHostKeyChecking=no \
                        -o UserKnownHostsFile=/dev/null \
                        ubuntu@$GREEN_HOST <<EOF

cd /home/ubuntu/graphic-design-tool/graphic-design-tool-main/Backend

echo "Current Directory:"
pwd

echo "Pulling latest code..."
git pull origin main

echo "Installing dependencies..."
npm install

echo "Restarting PM2..."
pm2 restart graphic-backend

echo "Backend deployment completed."

EOF
                    '''
                }
            }
        }

    }

    post {
        success {
            echo 'Backend deployed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }

        always {
            cleanWs()
        }
    }
}
